GET {{host}}/api/index.php/v1/ars/categories
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###

GET {{host}}/api/index.php/v1/ars/categories?search=Data+Compliance
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###

GET {{host}}/api/index.php/v1/ars/releases
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###

GET {{host}}/api/index.php/v1/ars/releases?category_id=1&search=version%3A1.0.0
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###

GET {{host}}/api/index.php/v1/ars/items?release_id=81&search=link:https://d16g1oj796wk12.cloudfront.net/downloads/test_package/2.0.0/pkg_test-core.zip
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###

GET {{host}}/api/index.php/v1/ars/items/161
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###
GET {{host}}/api/index.php/v1/ars/releases/81
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0

###

PATCH {{host}}/api/index.php/v1/ars/releases/81
Accept: application/vnd.api+json
X-Joomla-Token: {{token}}
User-Agent: AkeebaReleaseMaker/2.0
Content-Type: text/json

{
      "id": 81,
      "category_id": 1,
      "version": "3.0.0",
      "alias": "3-0-0",
      "maturity": "stable",
      "notes": "Once upon a time, in a galaxy far, far away someone created a random UUID4: {{$uuid}}",
      "hits": 0,
      "created": "2021-06-04 04:47:18",
      "created_by": 0,
      "modified": "2022-05-03 10:28:26",
      "modified_by": 70,
      "checked_out": 0,
      "checked_out_time": "0000-00-00 00:00:00",
      "ordering": 0,
      "access": 11,
      "show_unauth_links": 0,
      "redirect_unauth": "",
      "published": 1,
      "language": "*"
}

###
