<?xml version="1.0"?>
<!--~
  ~ @package   AkeebaReleaseSystem
  ~ @copyright Copyright (c)2010-2024 Nicholas K. Dionysopoulos / Akeeba Ltd
  ~ @license   GNU General Public License version 3, or later
  -->

<project name="AkeebaReleaseSystem" description="Akeeba Release System" default="git" >
	<import file="${phing.dir}/../buildfiles/phing/common.xml" />

	<fileset dir="${dirs.component}" id="component">
		<include name="api/**"/>
		<include name="backend/**"/>
		<include name="frontend/**"/>
		<include name="language/**"/>
		<include name="media/**"/>

		<include name="*"/>

		<exclude name="backend/views/**"/>
		<exclude name="frontend/views/**"/>

		<exclude name="cli/**"/>
		<exclude name="LICENSE.txt"/>
		<exclude name="script.ars.php"/>
	</fileset>

	<fileset dir="${dirs.release}" id="package">
		<include name="com_*.zip" />
		<include name="mod_*.zip" />
		<include name="plg_*.zip" />
		<include name="lib_*.zip" />
		<include name="file_fef*.zip" />
		<include name="pkg_*.xml" />
		<include name="language/**"/>
		<include name="*.txt" />
		<include name="script.ars.php" />
	</fileset>

	<target name="git" description="Makes only packages, not the documentation"
			depends="new-release,setup-properties,compile-javascript,compile-css,component-packages">
	</target>

	<target name="compile-javascript" description="Transpile and minify JavaScript files">
		<exec executable="${dirs.root}/../buildfiles/node_modules/.bin/babel"
			  dir="${dirs.root}" checkreturn="true">
			<env key="NODE_PATH" value="${dirs.root}/../buildfiles/node_modules" />

			<arg value="component/media/js" />

			<arg value="--config-file" />
			<arg value="${dirs.root}/.babelrc.json" />

			<arg value="--out-dir" />
			<arg value="component/media/js" />

			<arg value="--out-file-extension" />
			<arg value=".min.js" />

			<arg value="--source-maps" />
		</exec>
	</target>

	<target name="compile-css" description="Compile SCSS to minified CSS">
		<exec executable="sass" dir="${dirs.component}/media/css" checkreturn="true" passthru="true">
			<arg value="${dirs.component}/media/css:${dirs.component}/media/css" />
			<arg value="-s" />
			<arg value="compressed" />
		</exec>
	</target>
</project>
