/**
 * @package   AkeebaReleaseSystem
 * @copyright Copyright (c)2026 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license   GNU General Public License version 3, or later
 */

/**
 * @package   AkeebaReleaseSystem
 * @copyright Copyright (c)2024 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license   GNU General Public License version 3, or later
 */

-- UCM Content types (for tags)
DELETE FROM `#__content_types` WHERE `type_alias` = 'com_ars.category';
DELETE FROM `#__content_types` WHERE `type_alias` = 'com_ars.release';

INSERT INTO `#__content_types` (`type_id`, `type_title`, `type_alias`, `table`, `rules`, `field_mappings`, `router`, `content_history_options`) VALUES (19, 'ARS Category', 'com_ars.category', '{   		"special": {   			"dbtable": "#__ars_categories",   			"key": "id",   			"type": "CategoryTable",   			"prefix": "Akeeba\\\\Component\\\\ARS\\\\Administrator\\\\Table\\\\",   			"config": "array()"   		},   		"common": {   			"dbtable": "#__ucm_content",   			"key": "ucm_id",   			"type": "Corecontent",   			"prefix": "Joomla\\\\CMS\\\\Table\\\\",   			"config": "array()"   		}   	}', '', '{   		"common": {   			"core_content_item_id": "id",   			"core_title": "title",   			"core_state": "published",   			"core_alias": "alias",   			"core_created_time": "created",   			"core_modified_time": "modified",   			"core_body": "description",   			"core_hits": "null",   			"core_publish_up": "null",   			"core_publish_down": "null",   			"access": "access",   			"core_params": "null",   			"core_featured": "null",   			"core_metadata": "null",   			"core_language": "language",   			"core_images": "null",   			"core_urls": "null",   			"core_version": "null",   			"core_ordering": "ordering",   			"core_metakey": "null",   			"core_metadesc": "null",   			"core_catid": "null",   			"asset_id": "asset_id"   		},   		"special": {   			"type": "type",   			"directory": "directory",   			"show_unauth_links": "show_unauth_links",   			"redirect_unauth": "redirect_unauth",   			"is_supported": "is_supported"   		}   	}   ', 'Akeeba\\Component\\ATS\\Site\\Helper\\Route::getCategoryRoute', '');
INSERT INTO `#__content_types` (`type_id`, `type_title`, `type_alias`, `table`, `rules`, `field_mappings`, `router`, `content_history_options`) VALUES (20, 'ARS Release', 'com_ars.release', '{   		"special": {   			"dbtable": "#__ars_releases",   			"key": "id",   			"type": "ReleaseTable",   			"prefix": "Akeeba\\\\Component\\\\ARS\\\\Administrator\\\\Table\\\\",   			"config": "array()"   		},   		"common": {   			"dbtable": "#__ucm_content",   			"key": "ucm_id",   			"type": "Corecontent",   			"prefix": "Joomla\\\\CMS\\\\Table\\\\",   			"config": "array()"   		}   	}', '', '{   		"common": {   			"core_content_item_id": "id",   			"core_title": "version",   			"core_state": "published",   			"core_alias": "alias",   			"core_created_time": "created",   			"core_modified_time": "modified",   			"core_body": "notes",   			"core_hits": "hits",   			"core_publish_up": "null",   			"core_publish_down": "null",   			"access": "access",   			"core_params": "null",   			"core_featured": "null",   			"core_metadata": "null",   			"core_language": "language",   			"core_images": "null",   			"core_urls": "null",   			"core_version": "null",   			"core_ordering": "ordering",   			"core_metakey": "null",   			"core_metadesc": "null",   			"core_catid": "null",   			"asset_id": "null"   		},   		"special": {   			"category_id": "category_id",   			"maturity": "maturity",   			"show_unauth_links": "show_unauth_links",   			"redirect_unauth": "redirect_unauth"   		}   	}','Akeeba\\Component\\ATS\\Site\\Helper\\Route::getReleaseRoute', '');
